services:
  db:
    image: postgres:17-alpine
    container_name: buffet-pass-db
    environment:
      POSTGRES_USER: buffet
      POSTGRES_PASSWORD: buffet
      POSTGRES_DB: buffet
    ports:
      - "5432:5432"
    volumes:
      - buffet-pass-db:/var/lib/postgresql/data

volumes:
  buffet-pass-db:
